### ISSUE TITLE
Codimd rename to HedgeDoc

### ISSUE THREAD

**Issue by kosssi** [linuxserver/docker-codimd#17]
Hello linuxserver team,

I wanted to tell you CodiMD was renamed to HedgeDoc. [Read more](https://hedgedoc.org/history/).

It's only [1.7.0-rc1](https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.0-rc1) but you can think about the future of this package ;)

Thanks for your jobs

**Comment by aptalca** [comment]
Thanks for the heads up and congrats on the new home and rebranding. We'll look into it shortly

**Comment by aptalca** [comment]
@kosssi a few things. . .
I am working on a brand new image for HedgeDoc: https://github.com/linuxserver/docker-hedgedoc/tree/initial and once it's ready, we can deprecate CodiMD and start pushing users to the new image, which will be published at the `linuxserver/hedgedoc` endpoint.

But I have a couple of questions.

Is the new prerelease safe to update from the old codimd? Should I try to leave a clear in place update path from the codimd image to the new hedgedoc?
Also, do you guys have a donation link? If so, we can display that on our repo's Github sponsorship info as well as in the container log.

And one other thing, just fyi, your forum at https://community.hedgedoc.org/ seems to be having cert issues and due to hsts being enabled, users can't access at all

**Comment by mrdrogdrog** [comment]
Hi! I'm from the hedgedoc core dev team. I'll try to answer some of the questions.

> Is the new prerelease safe to update from the old codimd?

No, it's only a release candidate. Don't expect it to be stable. But our plan is to release the stable, tested version in some weeks but before 2021.

> Also, do you guys have a donation link?

No, right now we don't take any donations.

> And one other thing, just fyi, your forum at https://community.hedgedoc.org/ seems to be having cert issues and due to hsts being enabled, users can't access at all

Our hoster had some troubles while moving the discourse to the new domain 😅  It should be okay now.

**Comment by mrdrogdrog** [comment]
Regarding the first point: There are no special treatments necessary to update from codimd 1.6.0 to hedgedoc 1.7.0

**Comment by j0nnymoe** [comment]
@mrdrogdrog Thanks for the reply. Just a comment about donations, we can highly recommend using OpenCollective for this, Takes alot of the stress/hassle out of accepting them.
